package com.stc.echannels.epayments.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.stc.echannels.epayments.model.BankServices;
import com.stc.echannels.epayments.service.BankServicesLocalServiceUtil;

/**
 * The extended model base implementation for the BankServices service. Represents a row in the &quot;BANK_SERVICES_MAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankServicesImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see BankServicesImpl
 * @see com.stc.echannels.epayments.model.BankServices
 * @generated
 */
public abstract class BankServicesBaseImpl extends BankServicesModelImpl
    implements BankServices {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bank services model instance should use the {@link BankServices} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BankServicesLocalServiceUtil.addBankServices(this);
        } else {
            BankServicesLocalServiceUtil.updateBankServices(this);
        }
    }
}
