package com.stc.echannels.epayments.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.stc.echannels.epayments.model.CardGroup;
import com.stc.echannels.epayments.service.CardGroupLocalServiceUtil;

/**
 * The extended model base implementation for the CardGroup service. Represents a row in the &quot;IN_CARD_GROUPS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CardGroupImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see CardGroupImpl
 * @see com.stc.echannels.epayments.model.CardGroup
 * @generated
 */
public abstract class CardGroupBaseImpl extends CardGroupModelImpl
    implements CardGroup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a card group model instance should use the {@link CardGroup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CardGroupLocalServiceUtil.addCardGroup(this);
        } else {
            CardGroupLocalServiceUtil.updateCardGroup(this);
        }
    }
}
