package com.stc.echannels.epayments.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.stc.echannels.epayments.model.EPayAccessControl;
import com.stc.echannels.epayments.model.EPayAccessControlModel;
import com.stc.echannels.epayments.model.EPayAccessControlSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EPayAccessControl service. Represents a row in the &quot;EPAY_ACCESS_CONTROL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.stc.echannels.epayments.model.EPayAccessControlModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EPayAccessControlImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see EPayAccessControlImpl
 * @see com.stc.echannels.epayments.model.EPayAccessControl
 * @see com.stc.echannels.epayments.model.EPayAccessControlModel
 * @generated
 */
@JSON(strict = true)
public class EPayAccessControlModelImpl extends BaseModelImpl<EPayAccessControl>
    implements EPayAccessControlModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a e pay access control model instance should use the {@link com.stc.echannels.epayments.model.EPayAccessControl} interface instead.
     */
    public static final String TABLE_NAME = "EPAY_ACCESS_CONTROL";
    public static final Object[][] TABLE_COLUMNS = {
            { "EPAY_CONFIG_ID", Types.BIGINT },
            { "SERVICE_ID", Types.BIGINT },
            { "SERVICE_TYPE_ID", Types.BIGINT },
            { "CHANNEL_ID", Types.BIGINT },
            { "PMT_METHOD_ID", Types.BIGINT },
            { "TRANS_ID", Types.VARCHAR },
            { "CLIENT_IP", Types.VARCHAR },
            { "SERVER_IP", Types.VARCHAR },
            { "USER_AGENT", Types.VARCHAR },
            { "OPERATION", Types.VARCHAR },
            { "last_update_timestamp", Types.TIMESTAMP },
            { "last_update_userid", Types.VARCHAR },
            { "last_update_username", Types.VARCHAR },
            { "status", Types.VARCHAR },
            { "effective_timestamp", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table EPAY_ACCESS_CONTROL (EPAY_CONFIG_ID LONG not null primary key,SERVICE_ID LONG,SERVICE_TYPE_ID LONG,CHANNEL_ID LONG,PMT_METHOD_ID LONG,TRANS_ID VARCHAR(75) null,CLIENT_IP VARCHAR(75) null,SERVER_IP VARCHAR(75) null,USER_AGENT VARCHAR(75) null,OPERATION VARCHAR(75) null,last_update_timestamp DATE null,last_update_userid VARCHAR(75) null,last_update_username VARCHAR(75) null,status VARCHAR(75) null,effective_timestamp DATE null)";
    public static final String TABLE_SQL_DROP = "drop table EPAY_ACCESS_CONTROL";
    public static final String ORDER_BY_JPQL = " ORDER BY ePayAccessControl.epayCofignId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY EPAY_ACCESS_CONTROL.EPAY_CONFIG_ID ASC";
    public static final String DATA_SOURCE = "anotherDataSource";
    public static final String SESSION_FACTORY = "anotherSessionFactory";
    public static final String TX_MANAGER = "anotherTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.stc.echannels.epayments.model.EPayAccessControl"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.stc.echannels.epayments.model.EPayAccessControl"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.stc.echannels.epayments.model.EPayAccessControl"),
            true);
    public static long SERVICEID_COLUMN_BITMASK = 1L;
    public static long STATUS_COLUMN_BITMASK = 2L;
    public static long EPAYCOFIGNID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.stc.echannels.epayments.model.EPayAccessControl"));
    private static ClassLoader _classLoader = EPayAccessControl.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            EPayAccessControl.class
        };
    private long _epayCofignId;
    private long _serviceId;
    private long _originalServiceId;
    private boolean _setOriginalServiceId;
    private long _serviceTypeId;
    private long _channelId;
    private long _pmtMethodId;
    private String _transId;
    private String _clientIP;
    private String _serverIP;
    private String _userAgent;
    private String _operation;
    private Date _lastUpdateTimestamp;
    private String _lastUpdateUserid;
    private String _lastUpdateUsername;
    private String _status;
    private String _originalStatus;
    private Date _effectiveTimestamp;
    private long _columnBitmask;
    private EPayAccessControl _escapedModel;

    public EPayAccessControlModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static EPayAccessControl toModel(EPayAccessControlSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        EPayAccessControl model = new EPayAccessControlImpl();

        model.setEpayCofignId(soapModel.getEpayCofignId());
        model.setServiceId(soapModel.getServiceId());
        model.setServiceTypeId(soapModel.getServiceTypeId());
        model.setChannelId(soapModel.getChannelId());
        model.setPmtMethodId(soapModel.getPmtMethodId());
        model.setTransId(soapModel.getTransId());
        model.setClientIP(soapModel.getClientIP());
        model.setServerIP(soapModel.getServerIP());
        model.setUserAgent(soapModel.getUserAgent());
        model.setOperation(soapModel.getOperation());
        model.setLastUpdateTimestamp(soapModel.getLastUpdateTimestamp());
        model.setLastUpdateUserid(soapModel.getLastUpdateUserid());
        model.setLastUpdateUsername(soapModel.getLastUpdateUsername());
        model.setStatus(soapModel.getStatus());
        model.setEffectiveTimestamp(soapModel.getEffectiveTimestamp());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<EPayAccessControl> toModels(
        EPayAccessControlSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<EPayAccessControl> models = new ArrayList<EPayAccessControl>(soapModels.length);

        for (EPayAccessControlSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _epayCofignId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setEpayCofignId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _epayCofignId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return EPayAccessControl.class;
    }

    @Override
    public String getModelClassName() {
        return EPayAccessControl.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("epayCofignId", getEpayCofignId());
        attributes.put("serviceId", getServiceId());
        attributes.put("serviceTypeId", getServiceTypeId());
        attributes.put("channelId", getChannelId());
        attributes.put("pmtMethodId", getPmtMethodId());
        attributes.put("transId", getTransId());
        attributes.put("clientIP", getClientIP());
        attributes.put("serverIP", getServerIP());
        attributes.put("userAgent", getUserAgent());
        attributes.put("operation", getOperation());
        attributes.put("lastUpdateTimestamp", getLastUpdateTimestamp());
        attributes.put("lastUpdateUserid", getLastUpdateUserid());
        attributes.put("lastUpdateUsername", getLastUpdateUsername());
        attributes.put("status", getStatus());
        attributes.put("effectiveTimestamp", getEffectiveTimestamp());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long epayCofignId = (Long) attributes.get("epayCofignId");

        if (epayCofignId != null) {
            setEpayCofignId(epayCofignId);
        }

        Long serviceId = (Long) attributes.get("serviceId");

        if (serviceId != null) {
            setServiceId(serviceId);
        }

        Long serviceTypeId = (Long) attributes.get("serviceTypeId");

        if (serviceTypeId != null) {
            setServiceTypeId(serviceTypeId);
        }

        Long channelId = (Long) attributes.get("channelId");

        if (channelId != null) {
            setChannelId(channelId);
        }

        Long pmtMethodId = (Long) attributes.get("pmtMethodId");

        if (pmtMethodId != null) {
            setPmtMethodId(pmtMethodId);
        }

        String transId = (String) attributes.get("transId");

        if (transId != null) {
            setTransId(transId);
        }

        String clientIP = (String) attributes.get("clientIP");

        if (clientIP != null) {
            setClientIP(clientIP);
        }

        String serverIP = (String) attributes.get("serverIP");

        if (serverIP != null) {
            setServerIP(serverIP);
        }

        String userAgent = (String) attributes.get("userAgent");

        if (userAgent != null) {
            setUserAgent(userAgent);
        }

        String operation = (String) attributes.get("operation");

        if (operation != null) {
            setOperation(operation);
        }

        Date lastUpdateTimestamp = (Date) attributes.get("lastUpdateTimestamp");

        if (lastUpdateTimestamp != null) {
            setLastUpdateTimestamp(lastUpdateTimestamp);
        }

        String lastUpdateUserid = (String) attributes.get("lastUpdateUserid");

        if (lastUpdateUserid != null) {
            setLastUpdateUserid(lastUpdateUserid);
        }

        String lastUpdateUsername = (String) attributes.get(
                "lastUpdateUsername");

        if (lastUpdateUsername != null) {
            setLastUpdateUsername(lastUpdateUsername);
        }

        String status = (String) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }

        Date effectiveTimestamp = (Date) attributes.get("effectiveTimestamp");

        if (effectiveTimestamp != null) {
            setEffectiveTimestamp(effectiveTimestamp);
        }
    }

    @JSON
    @Override
    public long getEpayCofignId() {
        return _epayCofignId;
    }

    @Override
    public void setEpayCofignId(long epayCofignId) {
        _epayCofignId = epayCofignId;
    }

    @JSON
    @Override
    public long getServiceId() {
        return _serviceId;
    }

    @Override
    public void setServiceId(long serviceId) {
        _columnBitmask |= SERVICEID_COLUMN_BITMASK;

        if (!_setOriginalServiceId) {
            _setOriginalServiceId = true;

            _originalServiceId = _serviceId;
        }

        _serviceId = serviceId;
    }

    public long getOriginalServiceId() {
        return _originalServiceId;
    }

    @JSON
    @Override
    public long getServiceTypeId() {
        return _serviceTypeId;
    }

    @Override
    public void setServiceTypeId(long serviceTypeId) {
        _serviceTypeId = serviceTypeId;
    }

    @JSON
    @Override
    public long getChannelId() {
        return _channelId;
    }

    @Override
    public void setChannelId(long channelId) {
        _channelId = channelId;
    }

    @JSON
    @Override
    public long getPmtMethodId() {
        return _pmtMethodId;
    }

    @Override
    public void setPmtMethodId(long pmtMethodId) {
        _pmtMethodId = pmtMethodId;
    }

    @JSON
    @Override
    public String getTransId() {
        if (_transId == null) {
            return StringPool.BLANK;
        } else {
            return _transId;
        }
    }

    @Override
    public void setTransId(String transId) {
        _transId = transId;
    }

    @JSON
    @Override
    public String getClientIP() {
        if (_clientIP == null) {
            return StringPool.BLANK;
        } else {
            return _clientIP;
        }
    }

    @Override
    public void setClientIP(String clientIP) {
        _clientIP = clientIP;
    }

    @JSON
    @Override
    public String getServerIP() {
        if (_serverIP == null) {
            return StringPool.BLANK;
        } else {
            return _serverIP;
        }
    }

    @Override
    public void setServerIP(String serverIP) {
        _serverIP = serverIP;
    }

    @JSON
    @Override
    public String getUserAgent() {
        if (_userAgent == null) {
            return StringPool.BLANK;
        } else {
            return _userAgent;
        }
    }

    @Override
    public void setUserAgent(String userAgent) {
        _userAgent = userAgent;
    }

    @JSON
    @Override
    public String getOperation() {
        if (_operation == null) {
            return StringPool.BLANK;
        } else {
            return _operation;
        }
    }

    @Override
    public void setOperation(String operation) {
        _operation = operation;
    }

    @JSON
    @Override
    public Date getLastUpdateTimestamp() {
        return _lastUpdateTimestamp;
    }

    @Override
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
        _lastUpdateTimestamp = lastUpdateTimestamp;
    }

    @JSON
    @Override
    public String getLastUpdateUserid() {
        if (_lastUpdateUserid == null) {
            return StringPool.BLANK;
        } else {
            return _lastUpdateUserid;
        }
    }

    @Override
    public void setLastUpdateUserid(String lastUpdateUserid) {
        _lastUpdateUserid = lastUpdateUserid;
    }

    @JSON
    @Override
    public String getLastUpdateUsername() {
        if (_lastUpdateUsername == null) {
            return StringPool.BLANK;
        } else {
            return _lastUpdateUsername;
        }
    }

    @Override
    public void setLastUpdateUsername(String lastUpdateUsername) {
        _lastUpdateUsername = lastUpdateUsername;
    }

    @JSON
    @Override
    public String getStatus() {
        if (_status == null) {
            return StringPool.BLANK;
        } else {
            return _status;
        }
    }

    @Override
    public void setStatus(String status) {
        _columnBitmask |= STATUS_COLUMN_BITMASK;

        if (_originalStatus == null) {
            _originalStatus = _status;
        }

        _status = status;
    }

    public String getOriginalStatus() {
        return GetterUtil.getString(_originalStatus);
    }

    @JSON
    @Override
    public Date getEffectiveTimestamp() {
        return _effectiveTimestamp;
    }

    @Override
    public void setEffectiveTimestamp(Date effectiveTimestamp) {
        _effectiveTimestamp = effectiveTimestamp;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            EPayAccessControl.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public EPayAccessControl toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (EPayAccessControl) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        EPayAccessControlImpl ePayAccessControlImpl = new EPayAccessControlImpl();

        ePayAccessControlImpl.setEpayCofignId(getEpayCofignId());
        ePayAccessControlImpl.setServiceId(getServiceId());
        ePayAccessControlImpl.setServiceTypeId(getServiceTypeId());
        ePayAccessControlImpl.setChannelId(getChannelId());
        ePayAccessControlImpl.setPmtMethodId(getPmtMethodId());
        ePayAccessControlImpl.setTransId(getTransId());
        ePayAccessControlImpl.setClientIP(getClientIP());
        ePayAccessControlImpl.setServerIP(getServerIP());
        ePayAccessControlImpl.setUserAgent(getUserAgent());
        ePayAccessControlImpl.setOperation(getOperation());
        ePayAccessControlImpl.setLastUpdateTimestamp(getLastUpdateTimestamp());
        ePayAccessControlImpl.setLastUpdateUserid(getLastUpdateUserid());
        ePayAccessControlImpl.setLastUpdateUsername(getLastUpdateUsername());
        ePayAccessControlImpl.setStatus(getStatus());
        ePayAccessControlImpl.setEffectiveTimestamp(getEffectiveTimestamp());

        ePayAccessControlImpl.resetOriginalValues();

        return ePayAccessControlImpl;
    }

    @Override
    public int compareTo(EPayAccessControl ePayAccessControl) {
        long primaryKey = ePayAccessControl.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof EPayAccessControl)) {
            return false;
        }

        EPayAccessControl ePayAccessControl = (EPayAccessControl) obj;

        long primaryKey = ePayAccessControl.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        EPayAccessControlModelImpl ePayAccessControlModelImpl = this;

        ePayAccessControlModelImpl._originalServiceId = ePayAccessControlModelImpl._serviceId;

        ePayAccessControlModelImpl._setOriginalServiceId = false;

        ePayAccessControlModelImpl._originalStatus = ePayAccessControlModelImpl._status;

        ePayAccessControlModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<EPayAccessControl> toCacheModel() {
        EPayAccessControlCacheModel ePayAccessControlCacheModel = new EPayAccessControlCacheModel();

        ePayAccessControlCacheModel.epayCofignId = getEpayCofignId();

        ePayAccessControlCacheModel.serviceId = getServiceId();

        ePayAccessControlCacheModel.serviceTypeId = getServiceTypeId();

        ePayAccessControlCacheModel.channelId = getChannelId();

        ePayAccessControlCacheModel.pmtMethodId = getPmtMethodId();

        ePayAccessControlCacheModel.transId = getTransId();

        String transId = ePayAccessControlCacheModel.transId;

        if ((transId != null) && (transId.length() == 0)) {
            ePayAccessControlCacheModel.transId = null;
        }

        ePayAccessControlCacheModel.clientIP = getClientIP();

        String clientIP = ePayAccessControlCacheModel.clientIP;

        if ((clientIP != null) && (clientIP.length() == 0)) {
            ePayAccessControlCacheModel.clientIP = null;
        }

        ePayAccessControlCacheModel.serverIP = getServerIP();

        String serverIP = ePayAccessControlCacheModel.serverIP;

        if ((serverIP != null) && (serverIP.length() == 0)) {
            ePayAccessControlCacheModel.serverIP = null;
        }

        ePayAccessControlCacheModel.userAgent = getUserAgent();

        String userAgent = ePayAccessControlCacheModel.userAgent;

        if ((userAgent != null) && (userAgent.length() == 0)) {
            ePayAccessControlCacheModel.userAgent = null;
        }

        ePayAccessControlCacheModel.operation = getOperation();

        String operation = ePayAccessControlCacheModel.operation;

        if ((operation != null) && (operation.length() == 0)) {
            ePayAccessControlCacheModel.operation = null;
        }

        Date lastUpdateTimestamp = getLastUpdateTimestamp();

        if (lastUpdateTimestamp != null) {
            ePayAccessControlCacheModel.lastUpdateTimestamp = lastUpdateTimestamp.getTime();
        } else {
            ePayAccessControlCacheModel.lastUpdateTimestamp = Long.MIN_VALUE;
        }

        ePayAccessControlCacheModel.lastUpdateUserid = getLastUpdateUserid();

        String lastUpdateUserid = ePayAccessControlCacheModel.lastUpdateUserid;

        if ((lastUpdateUserid != null) && (lastUpdateUserid.length() == 0)) {
            ePayAccessControlCacheModel.lastUpdateUserid = null;
        }

        ePayAccessControlCacheModel.lastUpdateUsername = getLastUpdateUsername();

        String lastUpdateUsername = ePayAccessControlCacheModel.lastUpdateUsername;

        if ((lastUpdateUsername != null) && (lastUpdateUsername.length() == 0)) {
            ePayAccessControlCacheModel.lastUpdateUsername = null;
        }

        ePayAccessControlCacheModel.status = getStatus();

        String status = ePayAccessControlCacheModel.status;

        if ((status != null) && (status.length() == 0)) {
            ePayAccessControlCacheModel.status = null;
        }

        Date effectiveTimestamp = getEffectiveTimestamp();

        if (effectiveTimestamp != null) {
            ePayAccessControlCacheModel.effectiveTimestamp = effectiveTimestamp.getTime();
        } else {
            ePayAccessControlCacheModel.effectiveTimestamp = Long.MIN_VALUE;
        }

        return ePayAccessControlCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(31);

        sb.append("{epayCofignId=");
        sb.append(getEpayCofignId());
        sb.append(", serviceId=");
        sb.append(getServiceId());
        sb.append(", serviceTypeId=");
        sb.append(getServiceTypeId());
        sb.append(", channelId=");
        sb.append(getChannelId());
        sb.append(", pmtMethodId=");
        sb.append(getPmtMethodId());
        sb.append(", transId=");
        sb.append(getTransId());
        sb.append(", clientIP=");
        sb.append(getClientIP());
        sb.append(", serverIP=");
        sb.append(getServerIP());
        sb.append(", userAgent=");
        sb.append(getUserAgent());
        sb.append(", operation=");
        sb.append(getOperation());
        sb.append(", lastUpdateTimestamp=");
        sb.append(getLastUpdateTimestamp());
        sb.append(", lastUpdateUserid=");
        sb.append(getLastUpdateUserid());
        sb.append(", lastUpdateUsername=");
        sb.append(getLastUpdateUsername());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append(", effectiveTimestamp=");
        sb.append(getEffectiveTimestamp());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(49);

        sb.append("<model><model-name>");
        sb.append("com.stc.echannels.epayments.model.EPayAccessControl");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>epayCofignId</column-name><column-value><![CDATA[");
        sb.append(getEpayCofignId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serviceId</column-name><column-value><![CDATA[");
        sb.append(getServiceId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serviceTypeId</column-name><column-value><![CDATA[");
        sb.append(getServiceTypeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>channelId</column-name><column-value><![CDATA[");
        sb.append(getChannelId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>pmtMethodId</column-name><column-value><![CDATA[");
        sb.append(getPmtMethodId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>transId</column-name><column-value><![CDATA[");
        sb.append(getTransId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>clientIP</column-name><column-value><![CDATA[");
        sb.append(getClientIP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serverIP</column-name><column-value><![CDATA[");
        sb.append(getServerIP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userAgent</column-name><column-value><![CDATA[");
        sb.append(getUserAgent());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>operation</column-name><column-value><![CDATA[");
        sb.append(getOperation());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>lastUpdateTimestamp</column-name><column-value><![CDATA[");
        sb.append(getLastUpdateTimestamp());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>lastUpdateUserid</column-name><column-value><![CDATA[");
        sb.append(getLastUpdateUserid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>lastUpdateUsername</column-name><column-value><![CDATA[");
        sb.append(getLastUpdateUsername());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>effectiveTimestamp</column-name><column-value><![CDATA[");
        sb.append(getEffectiveTimestamp());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
