package com.stc.echannels.epayments.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.stc.echannels.epayments.model.InRechargeHistory;
import com.stc.echannels.epayments.service.InRechargeHistoryLocalServiceUtil;

/**
 * The extended model base implementation for the InRechargeHistory service. Represents a row in the &quot;IN_RECHARGES_HISTORY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InRechargeHistoryImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see InRechargeHistoryImpl
 * @see com.stc.echannels.epayments.model.InRechargeHistory
 * @generated
 */
public abstract class InRechargeHistoryBaseImpl
    extends InRechargeHistoryModelImpl implements InRechargeHistory {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a in recharge history model instance should use the {@link InRechargeHistory} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            InRechargeHistoryLocalServiceUtil.addInRechargeHistory(this);
        } else {
            InRechargeHistoryLocalServiceUtil.updateInRechargeHistory(this);
        }
    }
}
