package com.stc.echannels.epayments.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.stc.echannels.epayments.model.PaymentMethodSrvsMap;
import com.stc.echannels.epayments.service.PaymentMethodSrvsMapLocalServiceUtil;

/**
 * The extended model base implementation for the PaymentMethodSrvsMap service. Represents a row in the &quot;PAYMENT_METHOD_SERVICES_MAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentMethodSrvsMapImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see PaymentMethodSrvsMapImpl
 * @see com.stc.echannels.epayments.model.PaymentMethodSrvsMap
 * @generated
 */
public abstract class PaymentMethodSrvsMapBaseImpl
    extends PaymentMethodSrvsMapModelImpl implements PaymentMethodSrvsMap {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a payment method srvs map model instance should use the {@link PaymentMethodSrvsMap} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PaymentMethodSrvsMapLocalServiceUtil.addPaymentMethodSrvsMap(this);
        } else {
            PaymentMethodSrvsMapLocalServiceUtil.updatePaymentMethodSrvsMap(this);
        }
    }
}
