package com.stc.echannels.epayments.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.stc.echannels.epayments.model.RefundLog;
import com.stc.echannels.epayments.service.RefundLogLocalServiceUtil;

/**
 * The extended model base implementation for the RefundLog service. Represents a row in the &quot;REFUND_LOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RefundLogImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see RefundLogImpl
 * @see com.stc.echannels.epayments.model.RefundLog
 * @generated
 */
public abstract class RefundLogBaseImpl extends RefundLogModelImpl
    implements RefundLog {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a refund log model instance should use the {@link RefundLog} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RefundLogLocalServiceUtil.addRefundLog(this);
        } else {
            RefundLogLocalServiceUtil.updateRefundLog(this);
        }
    }
}
