/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.practicle.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the tops_user service. Represents a row in the &quot;tops_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.practicle.slayer.model.impl.tops_userModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.practicle.slayer.model.impl.tops_userImpl}.
 * </p>
 *
 * @author Ismail
 * @see tops_user
 * @see com.liferay.practicle.slayer.model.impl.tops_userImpl
 * @see com.liferay.practicle.slayer.model.impl.tops_userModelImpl
 * @generated
 */
public interface tops_userModel extends BaseModel<tops_user> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tops_user model instance should use the {@link tops_user} interface instead.
	 */

	/**
	 * Returns the primary key of this tops_user.
	 *
	 * @return the primary key of this tops_user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tops_user.
	 *
	 * @param primaryKey the primary key of this tops_user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tops_user ID of this tops_user.
	 *
	 * @return the tops_user ID of this tops_user
	 */
	public long getTops_userId();

	/**
	 * Sets the tops_user ID of this tops_user.
	 *
	 * @param tops_userId the tops_user ID of this tops_user
	 */
	public void setTops_userId(long tops_userId);

	/**
	 * Returns the firstname of this tops_user.
	 *
	 * @return the firstname of this tops_user
	 */
	@AutoEscape
	public String getFirstname();

	/**
	 * Sets the firstname of this tops_user.
	 *
	 * @param firstname the firstname of this tops_user
	 */
	public void setFirstname(String firstname);

	/**
	 * Returns the last name of this tops_user.
	 *
	 * @return the last name of this tops_user
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this tops_user.
	 *
	 * @param LastName the last name of this tops_user
	 */
	public void setLastName(String LastName);

	/**
	 * Returns the user name of this tops_user.
	 *
	 * @return the user name of this tops_user
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this tops_user.
	 *
	 * @param userName the user name of this tops_user
	 */
	public void setUserName(String userName);

	/**
	 * Returns the password of this tops_user.
	 *
	 * @return the password of this tops_user
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this tops_user.
	 *
	 * @param password the password of this tops_user
	 */
	public void setPassword(String password);

	/**
	 * Returns the email of this tops_user.
	 *
	 * @return the email of this tops_user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this tops_user.
	 *
	 * @param email the email of this tops_user
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this tops_user.
	 *
	 * @return the phone of this tops_user
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this tops_user.
	 *
	 * @param phone the phone of this tops_user
	 */
	public void setPhone(String phone);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tops_user tops_user);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tops_user> toCacheModel();

	@Override
	public tops_user toEscapedModel();

	@Override
	public tops_user toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}