/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.practical.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Orders service. Represents a row in the &quot;Orders&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.practical.model.impl.OrdersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.practical.model.impl.OrdersImpl}.
 * </p>
 *
 * @author saifulla
 * @see Orders
 * @see com.liferay.practical.model.impl.OrdersImpl
 * @see com.liferay.practical.model.impl.OrdersModelImpl
 * @generated
 */
public interface OrdersModel extends BaseModel<Orders> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a orders model instance should use the {@link Orders} interface instead.
	 */

	/**
	 * Returns the primary key of this orders.
	 *
	 * @return the primary key of this orders
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this orders.
	 *
	 * @param primaryKey the primary key of this orders
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the orderid of this orders.
	 *
	 * @return the orderid of this orders
	 */
	public long getOrderid();

	/**
	 * Sets the orderid of this orders.
	 *
	 * @param orderid the orderid of this orders
	 */
	public void setOrderid(long orderid);

	/**
	 * Returns the orderdate of this orders.
	 *
	 * @return the orderdate of this orders
	 */
	public Date getOrderdate();

	/**
	 * Sets the orderdate of this orders.
	 *
	 * @param orderdate the orderdate of this orders
	 */
	public void setOrderdate(Date orderdate);

	/**
	 * Returns the productname of this orders.
	 *
	 * @return the productname of this orders
	 */
	@AutoEscape
	public String getProductname();

	/**
	 * Sets the productname of this orders.
	 *
	 * @param productname the productname of this orders
	 */
	public void setProductname(String productname);

	/**
	 * Returns the productpackage of this orders.
	 *
	 * @return the productpackage of this orders
	 */
	@AutoEscape
	public String getProductpackage();

	/**
	 * Sets the productpackage of this orders.
	 *
	 * @param productpackage the productpackage of this orders
	 */
	public void setProductpackage(String productpackage);

	/**
	 * Returns the orderstatus of this orders.
	 *
	 * @return the orderstatus of this orders
	 */
	public int getOrderstatus();

	/**
	 * Sets the orderstatus of this orders.
	 *
	 * @param orderstatus the orderstatus of this orders
	 */
	public void setOrderstatus(int orderstatus);

	/**
	 * Returns the subscription of this orders.
	 *
	 * @return the subscription of this orders
	 */
	public boolean getSubscription();

	/**
	 * Returns <code>true</code> if this orders is subscription.
	 *
	 * @return <code>true</code> if this orders is subscription; <code>false</code> otherwise
	 */
	public boolean isSubscription();

	/**
	 * Sets whether this orders is subscription.
	 *
	 * @param Subscription the subscription of this orders
	 */
	public void setSubscription(boolean Subscription);

	/**
	 * Returns the documnetid of this orders.
	 *
	 * @return the documnetid of this orders
	 */
	public long getDocumnetid();

	/**
	 * Sets the documnetid of this orders.
	 *
	 * @param documnetid the documnetid of this orders
	 */
	public void setDocumnetid(long documnetid);

	/**
	 * Returns the status by user ID of this orders.
	 *
	 * @return the status by user ID of this orders
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this orders.
	 *
	 * @param statusByUserId the status by user ID of this orders
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this orders.
	 *
	 * @return the status by user uuid of this orders
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this orders.
	 *
	 * @param statusByUserUuid the status by user uuid of this orders
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this orders.
	 *
	 * @return the status date of this orders
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this orders.
	 *
	 * @param statusDate the status date of this orders
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the company ID of this orders.
	 *
	 * @return the company ID of this orders
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this orders.
	 *
	 * @param companyId the company ID of this orders
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this orders.
	 *
	 * @return the group ID of this orders
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this orders.
	 *
	 * @param groupId the group ID of this orders
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this orders.
	 *
	 * @return the user ID of this orders
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this orders.
	 *
	 * @param userId the user ID of this orders
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this orders.
	 *
	 * @return the user uuid of this orders
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this orders.
	 *
	 * @param userUuid the user uuid of this orders
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Orders orders);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Orders> toCacheModel();

	@Override
	public Orders toEscapedModel();

	@Override
	public Orders toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}