package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BankBranch service. Represents a row in the &quot;BRANCH_CODES_MAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.BankBranchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.BankBranchImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see BankBranch
 * @see com.stc.echannels.epayments.model.impl.BankBranchImpl
 * @see com.stc.echannels.epayments.model.impl.BankBranchModelImpl
 * @generated
 */
public interface BankBranchModel extends BaseModel<BankBranch> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a bank branch model instance should use the {@link BankBranch} interface instead.
     */

    /**
     * Returns the primary key of this bank branch.
     *
     * @return the primary key of this bank branch
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this bank branch.
     *
     * @param primaryKey the primary key of this bank branch
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the trans ID of this bank branch.
     *
     * @return the trans ID of this bank branch
     */
    @AutoEscape
    public String getTransId();

    /**
     * Sets the trans ID of this bank branch.
     *
     * @param transId the trans ID of this bank branch
     */
    public void setTransId(String transId);

    /**
     * Returns the stc branch code of this bank branch.
     *
     * @return the stc branch code of this bank branch
     */
    @AutoEscape
    public String getStcBranchCode();

    /**
     * Sets the stc branch code of this bank branch.
     *
     * @param stcBranchCode the stc branch code of this bank branch
     */
    public void setStcBranchCode(String stcBranchCode);

    /**
     * Returns the bank ID of this bank branch.
     *
     * @return the bank ID of this bank branch
     */
    @AutoEscape
    public String getBankId();

    /**
     * Sets the bank ID of this bank branch.
     *
     * @param bankId the bank ID of this bank branch
     */
    public void setBankId(String bankId);

    /**
     * Returns the channel ID of this bank branch.
     *
     * @return the channel ID of this bank branch
     */
    public long getChannelId();

    /**
     * Sets the channel ID of this bank branch.
     *
     * @param channelId the channel ID of this bank branch
     */
    public void setChannelId(long channelId);

    /**
     * Returns the last update timestamp of this bank branch.
     *
     * @return the last update timestamp of this bank branch
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this bank branch.
     *
     * @param lastUpdateTimestamp the last update timestamp of this bank branch
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this bank branch.
     *
     * @return the last update userid of this bank branch
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this bank branch.
     *
     * @param lastUpdateUserid the last update userid of this bank branch
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this bank branch.
     *
     * @return the last update username of this bank branch
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this bank branch.
     *
     * @param lastUpdateUsername the last update username of this bank branch
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the active of this bank branch.
     *
     * @return the active of this bank branch
     */
    @AutoEscape
    public String getActive();

    /**
     * Sets the active of this bank branch.
     *
     * @param active the active of this bank branch
     */
    public void setActive(String active);

    /**
     * Returns the status of this bank branch.
     *
     * @return the status of this bank branch
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this bank branch.
     *
     * @param status the status of this bank branch
     */
    public void setStatus(String status);

    /**
     * Returns the effective timestamp of this bank branch.
     *
     * @return the effective timestamp of this bank branch
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this bank branch.
     *
     * @param effectiveTimestamp the effective timestamp of this bank branch
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    /**
     * Returns the client ip of this bank branch.
     *
     * @return the client ip of this bank branch
     */
    @AutoEscape
    public String getClientIp();

    /**
     * Sets the client ip of this bank branch.
     *
     * @param clientIp the client ip of this bank branch
     */
    public void setClientIp(String clientIp);

    /**
     * Returns the server ip of this bank branch.
     *
     * @return the server ip of this bank branch
     */
    @AutoEscape
    public String getServerIp();

    /**
     * Sets the server ip of this bank branch.
     *
     * @param serverIp the server ip of this bank branch
     */
    public void setServerIp(String serverIp);

    /**
     * Returns the user agent of this bank branch.
     *
     * @return the user agent of this bank branch
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this bank branch.
     *
     * @param userAgent the user agent of this bank branch
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the operation of this bank branch.
     *
     * @return the operation of this bank branch
     */
    @AutoEscape
    public String getOperation();

    /**
     * Sets the operation of this bank branch.
     *
     * @param operation the operation of this bank branch
     */
    public void setOperation(String operation);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BankBranch bankBranch);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BankBranch> toCacheModel();

    @Override
    public BankBranch toEscapedModel();

    @Override
    public BankBranch toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
