package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BizRuleConfig service. Represents a row in the &quot;BIZ_RULE_CONFIG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.BizRuleConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.BizRuleConfigImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see BizRuleConfig
 * @see com.stc.echannels.epayments.model.impl.BizRuleConfigImpl
 * @see com.stc.echannels.epayments.model.impl.BizRuleConfigModelImpl
 * @generated
 */
public interface BizRuleConfigModel extends BaseModel<BizRuleConfig> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a biz rule config model instance should use the {@link BizRuleConfig} interface instead.
     */

    /**
     * Returns the primary key of this biz rule config.
     *
     * @return the primary key of this biz rule config
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this biz rule config.
     *
     * @param primaryKey the primary key of this biz rule config
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the biz rule ID of this biz rule config.
     *
     * @return the biz rule ID of this biz rule config
     */
    public long getBizRuleId();

    /**
     * Sets the biz rule ID of this biz rule config.
     *
     * @param bizRuleId the biz rule ID of this biz rule config
     */
    public void setBizRuleId(long bizRuleId);

    /**
     * Returns the service ID of this biz rule config.
     *
     * @return the service ID of this biz rule config
     */
    public long getServiceId();

    /**
     * Sets the service ID of this biz rule config.
     *
     * @param serviceId the service ID of this biz rule config
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the channel ID of this biz rule config.
     *
     * @return the channel ID of this biz rule config
     */
    public long getChannelId();

    /**
     * Sets the channel ID of this biz rule config.
     *
     * @param channelId the channel ID of this biz rule config
     */
    public void setChannelId(long channelId);

    /**
     * Returns the pmt method ID of this biz rule config.
     *
     * @return the pmt method ID of this biz rule config
     */
    public long getPmtMethodId();

    /**
     * Sets the pmt method ID of this biz rule config.
     *
     * @param pmtMethodId the pmt method ID of this biz rule config
     */
    public void setPmtMethodId(long pmtMethodId);

    /**
     * Returns the custom value of this biz rule config.
     *
     * @return the custom value of this biz rule config
     */
    @AutoEscape
    public String getCustomValue();

    /**
     * Sets the custom value of this biz rule config.
     *
     * @param customValue the custom value of this biz rule config
     */
    public void setCustomValue(String customValue);

    /**
     * Returns the rule ID of this biz rule config.
     *
     * @return the rule ID of this biz rule config
     */
    public long getRuleId();

    /**
     * Sets the rule ID of this biz rule config.
     *
     * @param ruleId the rule ID of this biz rule config
     */
    public void setRuleId(long ruleId);

    /**
     * Returns the trans ID of this biz rule config.
     *
     * @return the trans ID of this biz rule config
     */
    @AutoEscape
    public String getTransId();

    /**
     * Sets the trans ID of this biz rule config.
     *
     * @param transId the trans ID of this biz rule config
     */
    public void setTransId(String transId);

    /**
     * Returns the client i p of this biz rule config.
     *
     * @return the client i p of this biz rule config
     */
    @AutoEscape
    public String getClientIP();

    /**
     * Sets the client i p of this biz rule config.
     *
     * @param clientIP the client i p of this biz rule config
     */
    public void setClientIP(String clientIP);

    /**
     * Returns the server i p of this biz rule config.
     *
     * @return the server i p of this biz rule config
     */
    @AutoEscape
    public String getServerIP();

    /**
     * Sets the server i p of this biz rule config.
     *
     * @param serverIP the server i p of this biz rule config
     */
    public void setServerIP(String serverIP);

    /**
     * Returns the user agent of this biz rule config.
     *
     * @return the user agent of this biz rule config
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this biz rule config.
     *
     * @param userAgent the user agent of this biz rule config
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the operation of this biz rule config.
     *
     * @return the operation of this biz rule config
     */
    @AutoEscape
    public String getOperation();

    /**
     * Sets the operation of this biz rule config.
     *
     * @param operation the operation of this biz rule config
     */
    public void setOperation(String operation);

    /**
     * Returns the last update timestamp of this biz rule config.
     *
     * @return the last update timestamp of this biz rule config
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this biz rule config.
     *
     * @param lastUpdateTimestamp the last update timestamp of this biz rule config
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this biz rule config.
     *
     * @return the last update userid of this biz rule config
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this biz rule config.
     *
     * @param lastUpdateUserid the last update userid of this biz rule config
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this biz rule config.
     *
     * @return the last update username of this biz rule config
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this biz rule config.
     *
     * @param lastUpdateUsername the last update username of this biz rule config
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the status of this biz rule config.
     *
     * @return the status of this biz rule config
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this biz rule config.
     *
     * @param status the status of this biz rule config
     */
    public void setStatus(String status);

    /**
     * Returns the effective timestamp of this biz rule config.
     *
     * @return the effective timestamp of this biz rule config
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this biz rule config.
     *
     * @param effectiveTimestamp the effective timestamp of this biz rule config
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BizRuleConfig bizRuleConfig);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BizRuleConfig> toCacheModel();

    @Override
    public BizRuleConfig toEscapedModel();

    @Override
    public BizRuleConfig toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
