package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EPayAccessControl service. Represents a row in the &quot;EPAY_ACCESS_CONTROL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.EPayAccessControlModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.EPayAccessControlImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see EPayAccessControl
 * @see com.stc.echannels.epayments.model.impl.EPayAccessControlImpl
 * @see com.stc.echannels.epayments.model.impl.EPayAccessControlModelImpl
 * @generated
 */
public interface EPayAccessControlModel extends BaseModel<EPayAccessControl> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a e pay access control model instance should use the {@link EPayAccessControl} interface instead.
     */

    /**
     * Returns the primary key of this e pay access control.
     *
     * @return the primary key of this e pay access control
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this e pay access control.
     *
     * @param primaryKey the primary key of this e pay access control
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the epay cofign ID of this e pay access control.
     *
     * @return the epay cofign ID of this e pay access control
     */
    public long getEpayCofignId();

    /**
     * Sets the epay cofign ID of this e pay access control.
     *
     * @param epayCofignId the epay cofign ID of this e pay access control
     */
    public void setEpayCofignId(long epayCofignId);

    /**
     * Returns the service ID of this e pay access control.
     *
     * @return the service ID of this e pay access control
     */
    public long getServiceId();

    /**
     * Sets the service ID of this e pay access control.
     *
     * @param serviceId the service ID of this e pay access control
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the service type ID of this e pay access control.
     *
     * @return the service type ID of this e pay access control
     */
    public long getServiceTypeId();

    /**
     * Sets the service type ID of this e pay access control.
     *
     * @param serviceTypeId the service type ID of this e pay access control
     */
    public void setServiceTypeId(long serviceTypeId);

    /**
     * Returns the channel ID of this e pay access control.
     *
     * @return the channel ID of this e pay access control
     */
    public long getChannelId();

    /**
     * Sets the channel ID of this e pay access control.
     *
     * @param channelId the channel ID of this e pay access control
     */
    public void setChannelId(long channelId);

    /**
     * Returns the pmt method ID of this e pay access control.
     *
     * @return the pmt method ID of this e pay access control
     */
    public long getPmtMethodId();

    /**
     * Sets the pmt method ID of this e pay access control.
     *
     * @param pmtMethodId the pmt method ID of this e pay access control
     */
    public void setPmtMethodId(long pmtMethodId);

    /**
     * Returns the trans ID of this e pay access control.
     *
     * @return the trans ID of this e pay access control
     */
    @AutoEscape
    public String getTransId();

    /**
     * Sets the trans ID of this e pay access control.
     *
     * @param transId the trans ID of this e pay access control
     */
    public void setTransId(String transId);

    /**
     * Returns the client i p of this e pay access control.
     *
     * @return the client i p of this e pay access control
     */
    @AutoEscape
    public String getClientIP();

    /**
     * Sets the client i p of this e pay access control.
     *
     * @param clientIP the client i p of this e pay access control
     */
    public void setClientIP(String clientIP);

    /**
     * Returns the server i p of this e pay access control.
     *
     * @return the server i p of this e pay access control
     */
    @AutoEscape
    public String getServerIP();

    /**
     * Sets the server i p of this e pay access control.
     *
     * @param serverIP the server i p of this e pay access control
     */
    public void setServerIP(String serverIP);

    /**
     * Returns the user agent of this e pay access control.
     *
     * @return the user agent of this e pay access control
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this e pay access control.
     *
     * @param userAgent the user agent of this e pay access control
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the operation of this e pay access control.
     *
     * @return the operation of this e pay access control
     */
    @AutoEscape
    public String getOperation();

    /**
     * Sets the operation of this e pay access control.
     *
     * @param operation the operation of this e pay access control
     */
    public void setOperation(String operation);

    /**
     * Returns the last update timestamp of this e pay access control.
     *
     * @return the last update timestamp of this e pay access control
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this e pay access control.
     *
     * @param lastUpdateTimestamp the last update timestamp of this e pay access control
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this e pay access control.
     *
     * @return the last update userid of this e pay access control
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this e pay access control.
     *
     * @param lastUpdateUserid the last update userid of this e pay access control
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this e pay access control.
     *
     * @return the last update username of this e pay access control
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this e pay access control.
     *
     * @param lastUpdateUsername the last update username of this e pay access control
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the status of this e pay access control.
     *
     * @return the status of this e pay access control
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this e pay access control.
     *
     * @param status the status of this e pay access control
     */
    public void setStatus(String status);

    /**
     * Returns the effective timestamp of this e pay access control.
     *
     * @return the effective timestamp of this e pay access control
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this e pay access control.
     *
     * @param effectiveTimestamp the effective timestamp of this e pay access control
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EPayAccessControl ePayAccessControl);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EPayAccessControl> toCacheModel();

    @Override
    public EPayAccessControl toEscapedModel();

    @Override
    public EPayAccessControl toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
