package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NotifParam service. Represents a row in the &quot;NOTIF_PARAMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.NotifParamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.NotifParamImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see NotifParam
 * @see com.stc.echannels.epayments.model.impl.NotifParamImpl
 * @see com.stc.echannels.epayments.model.impl.NotifParamModelImpl
 * @generated
 */
public interface NotifParamModel extends BaseModel<NotifParam> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a notif param model instance should use the {@link NotifParam} interface instead.
     */

    /**
     * Returns the primary key of this notif param.
     *
     * @return the primary key of this notif param
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this notif param.
     *
     * @param primaryKey the primary key of this notif param
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the notif param ID of this notif param.
     *
     * @return the notif param ID of this notif param
     */
    public long getNotifParamId();

    /**
     * Sets the notif param ID of this notif param.
     *
     * @param notifParamId the notif param ID of this notif param
     */
    public void setNotifParamId(long notifParamId);

    /**
     * Returns the name ar of this notif param.
     *
     * @return the name ar of this notif param
     */
    @AutoEscape
    public String getNameAr();

    /**
     * Sets the name ar of this notif param.
     *
     * @param nameAr the name ar of this notif param
     */
    public void setNameAr(String nameAr);

    /**
     * Returns the name en of this notif param.
     *
     * @return the name en of this notif param
     */
    @AutoEscape
    public String getNameEn();

    /**
     * Sets the name en of this notif param.
     *
     * @param nameEn the name en of this notif param
     */
    public void setNameEn(String nameEn);

    /**
     * Returns the param name of this notif param.
     *
     * @return the param name of this notif param
     */
    @AutoEscape
    public String getParamName();

    /**
     * Sets the param name of this notif param.
     *
     * @param paramName the param name of this notif param
     */
    public void setParamName(String paramName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(NotifParam notifParam);

    @Override
    public int hashCode();

    @Override
    public CacheModel<NotifParam> toCacheModel();

    @Override
    public NotifParam toEscapedModel();

    @Override
    public NotifParam toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
