package com.stc.echannels.epayments.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.stc.echannels.epayments.service.persistence.NotifParamSrvPK;

import java.io.Serializable;

/**
 * The base model interface for the NotifParamSrv service. Represents a row in the &quot;NOTIF_PARAMS_SERVICES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.NotifParamSrvModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.NotifParamSrvImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see NotifParamSrv
 * @see com.stc.echannels.epayments.model.impl.NotifParamSrvImpl
 * @see com.stc.echannels.epayments.model.impl.NotifParamSrvModelImpl
 * @generated
 */
public interface NotifParamSrvModel extends BaseModel<NotifParamSrv> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a notif param srv model instance should use the {@link NotifParamSrv} interface instead.
     */

    /**
     * Returns the primary key of this notif param srv.
     *
     * @return the primary key of this notif param srv
     */
    public NotifParamSrvPK getPrimaryKey();

    /**
     * Sets the primary key of this notif param srv.
     *
     * @param primaryKey the primary key of this notif param srv
     */
    public void setPrimaryKey(NotifParamSrvPK primaryKey);

    /**
     * Returns the notif param ID of this notif param srv.
     *
     * @return the notif param ID of this notif param srv
     */
    public long getNotifParamId();

    /**
     * Sets the notif param ID of this notif param srv.
     *
     * @param notifParamId the notif param ID of this notif param srv
     */
    public void setNotifParamId(long notifParamId);

    /**
     * Returns the service ID of this notif param srv.
     *
     * @return the service ID of this notif param srv
     */
    public long getServiceId();

    /**
     * Sets the service ID of this notif param srv.
     *
     * @param serviceId the service ID of this notif param srv
     */
    public void setServiceId(long serviceId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(NotifParamSrv notifParamSrv);

    @Override
    public int hashCode();

    @Override
    public CacheModel<NotifParamSrv> toCacheModel();

    @Override
    public NotifParamSrv toEscapedModel();

    @Override
    public NotifParamSrv toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
