package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PaymentMethodSrvsMap service. Represents a row in the &quot;PAYMENT_METHOD_SERVICES_MAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.PaymentMethodSrvsMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.PaymentMethodSrvsMapImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see PaymentMethodSrvsMap
 * @see com.stc.echannels.epayments.model.impl.PaymentMethodSrvsMapImpl
 * @see com.stc.echannels.epayments.model.impl.PaymentMethodSrvsMapModelImpl
 * @generated
 */
public interface PaymentMethodSrvsMapModel extends BaseModel<PaymentMethodSrvsMap> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a payment method srvs map model instance should use the {@link PaymentMethodSrvsMap} interface instead.
     */

    /**
     * Returns the primary key of this payment method srvs map.
     *
     * @return the primary key of this payment method srvs map
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this payment method srvs map.
     *
     * @param primaryKey the primary key of this payment method srvs map
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the ID of this payment method srvs map.
     *
     * @return the ID of this payment method srvs map
     */
    @AutoEscape
    public String getId();

    /**
     * Sets the ID of this payment method srvs map.
     *
     * @param id the ID of this payment method srvs map
     */
    public void setId(String id);

    /**
     * Returns the service ID of this payment method srvs map.
     *
     * @return the service ID of this payment method srvs map
     */
    public long getServiceId();

    /**
     * Sets the service ID of this payment method srvs map.
     *
     * @param serviceId the service ID of this payment method srvs map
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the payment method ID of this payment method srvs map.
     *
     * @return the payment method ID of this payment method srvs map
     */
    public long getPaymentMethodId();

    /**
     * Sets the payment method ID of this payment method srvs map.
     *
     * @param paymentMethodId the payment method ID of this payment method srvs map
     */
    public void setPaymentMethodId(long paymentMethodId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PaymentMethodSrvsMap paymentMethodSrvsMap);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PaymentMethodSrvsMap> toCacheModel();

    @Override
    public PaymentMethodSrvsMap toEscapedModel();

    @Override
    public PaymentMethodSrvsMap toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
