package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentMethod service. Represents a row in the &quot;PAYMENT_METHODS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.PaymentMethodModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.PaymentMethodImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see PaymentMethod
 * @see com.stc.echannels.epayments.model.impl.PaymentMethodImpl
 * @see com.stc.echannels.epayments.model.impl.PaymentMethodModelImpl
 * @generated
 */
public interface PaymentMethodModel extends BaseModel<PaymentMethod> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a payment method model instance should use the {@link PaymentMethod} interface instead.
     */

    /**
     * Returns the primary key of this payment method.
     *
     * @return the primary key of this payment method
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this payment method.
     *
     * @param primaryKey the primary key of this payment method
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the pmt method ID of this payment method.
     *
     * @return the pmt method ID of this payment method
     */
    public long getPmtMethodId();

    /**
     * Sets the pmt method ID of this payment method.
     *
     * @param pmtMethodId the pmt method ID of this payment method
     */
    public void setPmtMethodId(long pmtMethodId);

    /**
     * Returns the status of this payment method.
     *
     * @return the status of this payment method
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this payment method.
     *
     * @param status the status of this payment method
     */
    public void setStatus(String status);

    /**
     * Returns the last update timestamp of this payment method.
     *
     * @return the last update timestamp of this payment method
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this payment method.
     *
     * @param lastUpdateTimestamp the last update timestamp of this payment method
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this payment method.
     *
     * @return the last update userid of this payment method
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this payment method.
     *
     * @param lastUpdateUserid the last update userid of this payment method
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this payment method.
     *
     * @return the last update username of this payment method
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this payment method.
     *
     * @param lastUpdateUsername the last update username of this payment method
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the effective timestamp of this payment method.
     *
     * @return the effective timestamp of this payment method
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this payment method.
     *
     * @param effectiveTimestamp the effective timestamp of this payment method
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    /**
     * Returns the client ip of this payment method.
     *
     * @return the client ip of this payment method
     */
    @AutoEscape
    public String getClientIp();

    /**
     * Sets the client ip of this payment method.
     *
     * @param clientIp the client ip of this payment method
     */
    public void setClientIp(String clientIp);

    /**
     * Returns the server ip of this payment method.
     *
     * @return the server ip of this payment method
     */
    @AutoEscape
    public String getServerIp();

    /**
     * Sets the server ip of this payment method.
     *
     * @param serverIp the server ip of this payment method
     */
    public void setServerIp(String serverIp);

    /**
     * Returns the user agent of this payment method.
     *
     * @return the user agent of this payment method
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this payment method.
     *
     * @param userAgent the user agent of this payment method
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the operation of this payment method.
     *
     * @return the operation of this payment method
     */
    @AutoEscape
    public String getOperation();

    /**
     * Sets the operation of this payment method.
     *
     * @param operation the operation of this payment method
     */
    public void setOperation(String operation);

    /**
     * Returns the descriptive name en of this payment method.
     *
     * @return the descriptive name en of this payment method
     */
    @AutoEscape
    public String getDescriptiveNameEn();

    /**
     * Sets the descriptive name en of this payment method.
     *
     * @param descriptiveNameEn the descriptive name en of this payment method
     */
    public void setDescriptiveNameEn(String descriptiveNameEn);

    /**
     * Returns the descriptive name ar of this payment method.
     *
     * @return the descriptive name ar of this payment method
     */
    @AutoEscape
    public String getDescriptiveNameAr();

    /**
     * Sets the descriptive name ar of this payment method.
     *
     * @param descriptiveNameAr the descriptive name ar of this payment method
     */
    public void setDescriptiveNameAr(String descriptiveNameAr);

    /**
     * Returns the pmt method ID type of this payment method.
     *
     * @return the pmt method ID type of this payment method
     */
    @AutoEscape
    public String getPmtMethodIdType();

    /**
     * Sets the pmt method ID type of this payment method.
     *
     * @param pmtMethodIdType the pmt method ID type of this payment method
     */
    public void setPmtMethodIdType(String pmtMethodIdType);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PaymentMethod paymentMethod);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PaymentMethod> toCacheModel();

    @Override
    public PaymentMethod toEscapedModel();

    @Override
    public PaymentMethod toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
