package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentChannel service. Represents a row in the &quot;PAYMENT_CHANNELS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.PaymentChannelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.PaymentChannelImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see PaymentChannel
 * @see com.stc.echannels.epayments.model.impl.PaymentChannelImpl
 * @see com.stc.echannels.epayments.model.impl.PaymentChannelModelImpl
 * @generated
 */
public interface PaymentChannelModel extends BaseModel<PaymentChannel> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a payment channel model instance should use the {@link PaymentChannel} interface instead.
     */

    /**
     * Returns the primary key of this payment channel.
     *
     * @return the primary key of this payment channel
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this payment channel.
     *
     * @param primaryKey the primary key of this payment channel
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the trans ID of this payment channel.
     *
     * @return the trans ID of this payment channel
     */
    @AutoEscape
    public String getTransId();

    /**
     * Sets the trans ID of this payment channel.
     *
     * @param transId the trans ID of this payment channel
     */
    public void setTransId(String transId);

    /**
     * Returns the last update timestamp of this payment channel.
     *
     * @return the last update timestamp of this payment channel
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this payment channel.
     *
     * @param lastUpdateTimestamp the last update timestamp of this payment channel
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this payment channel.
     *
     * @return the last update userid of this payment channel
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this payment channel.
     *
     * @param lastUpdateUserid the last update userid of this payment channel
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this payment channel.
     *
     * @return the last update username of this payment channel
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this payment channel.
     *
     * @param lastUpdateUsername the last update username of this payment channel
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the active of this payment channel.
     *
     * @return the active of this payment channel
     */
    @AutoEscape
    public String getActive();

    /**
     * Sets the active of this payment channel.
     *
     * @param active the active of this payment channel
     */
    public void setActive(String active);

    /**
     * Returns the status of this payment channel.
     *
     * @return the status of this payment channel
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this payment channel.
     *
     * @param status the status of this payment channel
     */
    public void setStatus(String status);

    /**
     * Returns the effective timestamp of this payment channel.
     *
     * @return the effective timestamp of this payment channel
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this payment channel.
     *
     * @param effectiveTimestamp the effective timestamp of this payment channel
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    /**
     * Returns the client ip of this payment channel.
     *
     * @return the client ip of this payment channel
     */
    @AutoEscape
    public String getClientIp();

    /**
     * Sets the client ip of this payment channel.
     *
     * @param clientIp the client ip of this payment channel
     */
    public void setClientIp(String clientIp);

    /**
     * Returns the server ip of this payment channel.
     *
     * @return the server ip of this payment channel
     */
    @AutoEscape
    public String getServerIp();

    /**
     * Sets the server ip of this payment channel.
     *
     * @param serverIp the server ip of this payment channel
     */
    public void setServerIp(String serverIp);

    /**
     * Returns the user agent of this payment channel.
     *
     * @return the user agent of this payment channel
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this payment channel.
     *
     * @param userAgent the user agent of this payment channel
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the operation of this payment channel.
     *
     * @return the operation of this payment channel
     */
    @AutoEscape
    public String getOperation();

    /**
     * Sets the operation of this payment channel.
     *
     * @param operation the operation of this payment channel
     */
    public void setOperation(String operation);

    /**
     * Returns the channel ID of this payment channel.
     *
     * @return the channel ID of this payment channel
     */
    public long getChannelId();

    /**
     * Sets the channel ID of this payment channel.
     *
     * @param channelId the channel ID of this payment channel
     */
    public void setChannelId(long channelId);

    /**
     * Returns the channel type of this payment channel.
     *
     * @return the channel type of this payment channel
     */
    @AutoEscape
    public String getChannelType();

    /**
     * Sets the channel type of this payment channel.
     *
     * @param channelType the channel type of this payment channel
     */
    public void setChannelType(String channelType);

    /**
     * Returns the descriptive name en of this payment channel.
     *
     * @return the descriptive name en of this payment channel
     */
    @AutoEscape
    public String getDescriptiveNameEn();

    /**
     * Sets the descriptive name en of this payment channel.
     *
     * @param descriptiveNameEn the descriptive name en of this payment channel
     */
    public void setDescriptiveNameEn(String descriptiveNameEn);

    /**
     * Returns the descriptive name ar of this payment channel.
     *
     * @return the descriptive name ar of this payment channel
     */
    @AutoEscape
    public String getDescriptiveNameAr();

    /**
     * Sets the descriptive name ar of this payment channel.
     *
     * @param descriptiveNameAr the descriptive name ar of this payment channel
     */
    public void setDescriptiveNameAr(String descriptiveNameAr);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PaymentChannel paymentChannel);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PaymentChannel> toCacheModel();

    @Override
    public PaymentChannel toEscapedModel();

    @Override
    public PaymentChannel toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
