package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentSystem service. Represents a row in the &quot;PAYMENT_SYSTEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.PaymentSystemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.PaymentSystemImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see PaymentSystem
 * @see com.stc.echannels.epayments.model.impl.PaymentSystemImpl
 * @see com.stc.echannels.epayments.model.impl.PaymentSystemModelImpl
 * @generated
 */
public interface PaymentSystemModel extends BaseModel<PaymentSystem> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a payment system model instance should use the {@link PaymentSystem} interface instead.
     */

    /**
     * Returns the primary key of this payment system.
     *
     * @return the primary key of this payment system
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this payment system.
     *
     * @param primaryKey the primary key of this payment system
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the payment system ID of this payment system.
     *
     * @return the payment system ID of this payment system
     */
    public long getPaymentSystemId();

    /**
     * Sets the payment system ID of this payment system.
     *
     * @param paymentSystemId the payment system ID of this payment system
     */
    public void setPaymentSystemId(long paymentSystemId);

    /**
     * Returns the last update timestamp of this payment system.
     *
     * @return the last update timestamp of this payment system
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this payment system.
     *
     * @param lastUpdateTimestamp the last update timestamp of this payment system
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this payment system.
     *
     * @return the last update userid of this payment system
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this payment system.
     *
     * @param lastUpdateUserid the last update userid of this payment system
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this payment system.
     *
     * @return the last update username of this payment system
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this payment system.
     *
     * @param lastUpdateUsername the last update username of this payment system
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the active of this payment system.
     *
     * @return the active of this payment system
     */
    @AutoEscape
    public String getActive();

    /**
     * Sets the active of this payment system.
     *
     * @param active the active of this payment system
     */
    public void setActive(String active);

    /**
     * Returns the effective timestamp of this payment system.
     *
     * @return the effective timestamp of this payment system
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this payment system.
     *
     * @param effectiveTimestamp the effective timestamp of this payment system
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    /**
     * Returns the system name of this payment system.
     *
     * @return the system name of this payment system
     */
    @AutoEscape
    public String getSystemName();

    /**
     * Sets the system name of this payment system.
     *
     * @param systemName the system name of this payment system
     */
    public void setSystemName(String systemName);

    /**
     * Returns the date format of this payment system.
     *
     * @return the date format of this payment system
     */
    @AutoEscape
    public String getDateFormat();

    /**
     * Sets the date format of this payment system.
     *
     * @param dateFormat the date format of this payment system
     */
    public void setDateFormat(String dateFormat);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PaymentSystem paymentSystem);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PaymentSystem> toCacheModel();

    @Override
    public PaymentSystem toEscapedModel();

    @Override
    public PaymentSystem toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
