package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PaymentChannelSr service. Represents a row in the &quot;PAYMENT_CHANNEL_SERVICES_MAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.PaymentChannelSrModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.PaymentChannelSrImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see PaymentChannelSr
 * @see com.stc.echannels.epayments.model.impl.PaymentChannelSrImpl
 * @see com.stc.echannels.epayments.model.impl.PaymentChannelSrModelImpl
 * @generated
 */
public interface PaymentChannelSrModel extends BaseModel<PaymentChannelSr> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a payment channel sr model instance should use the {@link PaymentChannelSr} interface instead.
     */

    /**
     * Returns the primary key of this payment channel sr.
     *
     * @return the primary key of this payment channel sr
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this payment channel sr.
     *
     * @param primaryKey the primary key of this payment channel sr
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the channelid of this payment channel sr.
     *
     * @return the channelid of this payment channel sr
     */
    public long getChannelid();

    /**
     * Sets the channelid of this payment channel sr.
     *
     * @param channelid the channelid of this payment channel sr
     */
    public void setChannelid(long channelid);

    /**
     * Returns the serviceid of this payment channel sr.
     *
     * @return the serviceid of this payment channel sr
     */
    public long getServiceid();

    /**
     * Sets the serviceid of this payment channel sr.
     *
     * @param serviceid the serviceid of this payment channel sr
     */
    public void setServiceid(long serviceid);

    /**
     * Returns the ID of this payment channel sr.
     *
     * @return the ID of this payment channel sr
     */
    @AutoEscape
    public String getId();

    /**
     * Sets the ID of this payment channel sr.
     *
     * @param id the ID of this payment channel sr
     */
    public void setId(String id);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PaymentChannelSr paymentChannelSr);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PaymentChannelSr> toCacheModel();

    @Override
    public PaymentChannelSr toEscapedModel();

    @Override
    public PaymentChannelSr toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
