package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ReconLog service. Represents a row in the &quot;SADAD_RECON_LOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.ReconLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.ReconLogImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see ReconLog
 * @see com.stc.echannels.epayments.model.impl.ReconLogImpl
 * @see com.stc.echannels.epayments.model.impl.ReconLogModelImpl
 * @generated
 */
public interface ReconLogModel extends BaseModel<ReconLog> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a recon log model instance should use the {@link ReconLog} interface instead.
     */

    /**
     * Returns the primary key of this recon log.
     *
     * @return the primary key of this recon log
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this recon log.
     *
     * @param primaryKey the primary key of this recon log
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the payment system trans ID of this recon log.
     *
     * @return the payment system trans ID of this recon log
     */
    @AutoEscape
    public String getPaymentSystemTransId();

    /**
     * Sets the payment system trans ID of this recon log.
     *
     * @param paymentSystemTransId the payment system trans ID of this recon log
     */
    public void setPaymentSystemTransId(String paymentSystemTransId);

    /**
     * Returns the bank trans ID of this recon log.
     *
     * @return the bank trans ID of this recon log
     */
    public long getBankTransId();

    /**
     * Sets the bank trans ID of this recon log.
     *
     * @param bankTransId the bank trans ID of this recon log
     */
    public void setBankTransId(long bankTransId);

    /**
     * Returns the trans amount of this recon log.
     *
     * @return the trans amount of this recon log
     */
    public double getTransAmount();

    /**
     * Sets the trans amount of this recon log.
     *
     * @param transAmount the trans amount of this recon log
     */
    public void setTransAmount(double transAmount);

    /**
     * Returns the payment method of this recon log.
     *
     * @return the payment method of this recon log
     */
    @AutoEscape
    public String getPaymentMethod();

    /**
     * Sets the payment method of this recon log.
     *
     * @param paymentMethod the payment method of this recon log
     */
    public void setPaymentMethod(String paymentMethod);

    /**
     * Returns the payment channel of this recon log.
     *
     * @return the payment channel of this recon log
     */
    @AutoEscape
    public String getPaymentChannel();

    /**
     * Sets the payment channel of this recon log.
     *
     * @param paymentChannel the payment channel of this recon log
     */
    public void setPaymentChannel(String paymentChannel);

    /**
     * Returns the pmt bank ID of this recon log.
     *
     * @return the pmt bank ID of this recon log
     */
    @AutoEscape
    public String getPmtBankId();

    /**
     * Sets the pmt bank ID of this recon log.
     *
     * @param pmtBankId the pmt bank ID of this recon log
     */
    public void setPmtBankId(String pmtBankId);

    /**
     * Returns the bank trans date of this recon log.
     *
     * @return the bank trans date of this recon log
     */
    public Date getBankTransDate();

    /**
     * Sets the bank trans date of this recon log.
     *
     * @param bankTransDate the bank trans date of this recon log
     */
    public void setBankTransDate(Date bankTransDate);

    /**
     * Returns the beneficiary service no of this recon log.
     *
     * @return the beneficiary service no of this recon log
     */
    @AutoEscape
    public String getBeneficiaryServiceNo();

    /**
     * Sets the beneficiary service no of this recon log.
     *
     * @param beneficiaryServiceNo the beneficiary service no of this recon log
     */
    public void setBeneficiaryServiceNo(String beneficiaryServiceNo);

    /**
     * Returns the service ID of this recon log.
     *
     * @return the service ID of this recon log
     */
    public long getServiceId();

    /**
     * Sets the service ID of this recon log.
     *
     * @param serviceId the service ID of this recon log
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the payment status of this recon log.
     *
     * @return the payment status of this recon log
     */
    @AutoEscape
    public String getPaymentStatus();

    /**
     * Sets the payment status of this recon log.
     *
     * @param paymentStatus the payment status of this recon log
     */
    public void setPaymentStatus(String paymentStatus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ReconLog reconLog);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ReconLog> toCacheModel();

    @Override
    public ReconLog toEscapedModel();

    @Override
    public ReconLog toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
