package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RefundReconLog service. Represents a row in the &quot;REFUND_RECON_LOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.RefundReconLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.RefundReconLogImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see RefundReconLog
 * @see com.stc.echannels.epayments.model.impl.RefundReconLogImpl
 * @see com.stc.echannels.epayments.model.impl.RefundReconLogModelImpl
 * @generated
 */
public interface RefundReconLogModel extends BaseModel<RefundReconLog> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a refund recon log model instance should use the {@link RefundReconLog} interface instead.
     */

    /**
     * Returns the primary key of this refund recon log.
     *
     * @return the primary key of this refund recon log
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this refund recon log.
     *
     * @param primaryKey the primary key of this refund recon log
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the batch ID of this refund recon log.
     *
     * @return the batch ID of this refund recon log
     */
    @AutoEscape
    public String getBatchId();

    /**
     * Sets the batch ID of this refund recon log.
     *
     * @param batchId the batch ID of this refund recon log
     */
    public void setBatchId(String batchId);

    /**
     * Returns the service ID of this refund recon log.
     *
     * @return the service ID of this refund recon log
     */
    public long getServiceId();

    /**
     * Sets the service ID of this refund recon log.
     *
     * @param serviceId the service ID of this refund recon log
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the refund ID of this refund recon log.
     *
     * @return the refund ID of this refund recon log
     */
    @AutoEscape
    public String getRefundId();

    /**
     * Sets the refund ID of this refund recon log.
     *
     * @param refundId the refund ID of this refund recon log
     */
    public void setRefundId(String refundId);

    /**
     * Returns the pmt bank ID of this refund recon log.
     *
     * @return the pmt bank ID of this refund recon log
     */
    @AutoEscape
    public String getPmtBankId();

    /**
     * Sets the pmt bank ID of this refund recon log.
     *
     * @param pmtBankId the pmt bank ID of this refund recon log
     */
    public void setPmtBankId(String pmtBankId);

    /**
     * Returns the pmt system refund trans ID of this refund recon log.
     *
     * @return the pmt system refund trans ID of this refund recon log
     */
    @AutoEscape
    public String getPmtSystemRefundTransId();

    /**
     * Sets the pmt system refund trans ID of this refund recon log.
     *
     * @param pmtSystemRefundTransId the pmt system refund trans ID of this refund recon log
     */
    public void setPmtSystemRefundTransId(String pmtSystemRefundTransId);

    /**
     * Returns the bank refund trans ID of this refund recon log.
     *
     * @return the bank refund trans ID of this refund recon log
     */
    @AutoEscape
    public String getBankRefundTransId();

    /**
     * Sets the bank refund trans ID of this refund recon log.
     *
     * @param bankRefundTransId the bank refund trans ID of this refund recon log
     */
    public void setBankRefundTransId(String bankRefundTransId);

    /**
     * Returns the eff dt of this refund recon log.
     *
     * @return the eff dt of this refund recon log
     */
    public Date getEffDt();

    /**
     * Sets the eff dt of this refund recon log.
     *
     * @param effDt the eff dt of this refund recon log
     */
    public void setEffDt(Date effDt);

    /**
     * Returns the process date of this refund recon log.
     *
     * @return the process date of this refund recon log
     */
    public Date getProcessDate();

    /**
     * Sets the process date of this refund recon log.
     *
     * @param processDate the process date of this refund recon log
     */
    public void setProcessDate(Date processDate);

    /**
     * Returns the refund amount of this refund recon log.
     *
     * @return the refund amount of this refund recon log
     */
    public double getRefundAmount();

    /**
     * Sets the refund amount of this refund recon log.
     *
     * @param refundAmount the refund amount of this refund recon log
     */
    public void setRefundAmount(double refundAmount);

    /**
     * Returns the refund status code of this refund recon log.
     *
     * @return the refund status code of this refund recon log
     */
    @AutoEscape
    public String getRefundStatusCode();

    /**
     * Sets the refund status code of this refund recon log.
     *
     * @param refundStatusCode the refund status code of this refund recon log
     */
    public void setRefundStatusCode(String refundStatusCode);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(RefundReconLog refundReconLog);

    @Override
    public int hashCode();

    @Override
    public CacheModel<RefundReconLog> toCacheModel();

    @Override
    public RefundReconLog toEscapedModel();

    @Override
    public RefundReconLog toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
