package com.stc.echannels.epayments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SystemConfig service. Represents a row in the &quot;SYSTEM_CONFIG_MGR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stc.echannels.epayments.model.impl.SystemConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stc.echannels.epayments.model.impl.SystemConfigImpl}.
 * </p>
 *
 * @author ahmed_fadlus
 * @see SystemConfig
 * @see com.stc.echannels.epayments.model.impl.SystemConfigImpl
 * @see com.stc.echannels.epayments.model.impl.SystemConfigModelImpl
 * @generated
 */
public interface SystemConfigModel extends BaseModel<SystemConfig> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a system config model instance should use the {@link SystemConfig} interface instead.
     */

    /**
     * Returns the primary key of this system config.
     *
     * @return the primary key of this system config
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this system config.
     *
     * @param primaryKey the primary key of this system config
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the trans ID of this system config.
     *
     * @return the trans ID of this system config
     */
    @AutoEscape
    public String getTransId();

    /**
     * Sets the trans ID of this system config.
     *
     * @param transId the trans ID of this system config
     */
    public void setTransId(String transId);

    /**
     * Returns the last update timestamp of this system config.
     *
     * @return the last update timestamp of this system config
     */
    public Date getLastUpdateTimestamp();

    /**
     * Sets the last update timestamp of this system config.
     *
     * @param lastUpdateTimestamp the last update timestamp of this system config
     */
    public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

    /**
     * Returns the last update userid of this system config.
     *
     * @return the last update userid of this system config
     */
    @AutoEscape
    public String getLastUpdateUserid();

    /**
     * Sets the last update userid of this system config.
     *
     * @param lastUpdateUserid the last update userid of this system config
     */
    public void setLastUpdateUserid(String lastUpdateUserid);

    /**
     * Returns the last update username of this system config.
     *
     * @return the last update username of this system config
     */
    @AutoEscape
    public String getLastUpdateUsername();

    /**
     * Sets the last update username of this system config.
     *
     * @param lastUpdateUsername the last update username of this system config
     */
    public void setLastUpdateUsername(String lastUpdateUsername);

    /**
     * Returns the status of this system config.
     *
     * @return the status of this system config
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this system config.
     *
     * @param status the status of this system config
     */
    public void setStatus(String status);

    /**
     * Returns the effective timestamp of this system config.
     *
     * @return the effective timestamp of this system config
     */
    public Date getEffectiveTimestamp();

    /**
     * Sets the effective timestamp of this system config.
     *
     * @param effectiveTimestamp the effective timestamp of this system config
     */
    public void setEffectiveTimestamp(Date effectiveTimestamp);

    /**
     * Returns the client ip of this system config.
     *
     * @return the client ip of this system config
     */
    @AutoEscape
    public String getClientIp();

    /**
     * Sets the client ip of this system config.
     *
     * @param clientIp the client ip of this system config
     */
    public void setClientIp(String clientIp);

    /**
     * Returns the server ip of this system config.
     *
     * @return the server ip of this system config
     */
    @AutoEscape
    public String getServerIp();

    /**
     * Sets the server ip of this system config.
     *
     * @param serverIp the server ip of this system config
     */
    public void setServerIp(String serverIp);

    /**
     * Returns the user agent of this system config.
     *
     * @return the user agent of this system config
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this system config.
     *
     * @param userAgent the user agent of this system config
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the operation of this system config.
     *
     * @return the operation of this system config
     */
    @AutoEscape
    public String getOperation();

    /**
     * Sets the operation of this system config.
     *
     * @param operation the operation of this system config
     */
    public void setOperation(String operation);

    /**
     * Returns the service ID of this system config.
     *
     * @return the service ID of this system config
     */
    public long getServiceId();

    /**
     * Sets the service ID of this system config.
     *
     * @param serviceId the service ID of this system config
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the bank ID of this system config.
     *
     * @return the bank ID of this system config
     */
    @AutoEscape
    public String getBankId();

    /**
     * Sets the bank ID of this system config.
     *
     * @param bankId the bank ID of this system config
     */
    public void setBankId(String bankId);

    /**
     * Returns the config of this system config.
     *
     * @return the config of this system config
     */
    @AutoEscape
    public String getConfig();

    /**
     * Sets the config of this system config.
     *
     * @param config the config of this system config
     */
    public void setConfig(String config);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(SystemConfig systemConfig);

    @Override
    public int hashCode();

    @Override
    public CacheModel<SystemConfig> toCacheModel();

    @Override
    public SystemConfig toEscapedModel();

    @Override
    public SystemConfig toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
